# Generated by Django 4.2.10 on 2026-06-16 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GlazeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('retest_cycle_days', models.IntegerField(default=30)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KilnBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('firing_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-firing_date', 'batch_code'],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('temperature_range', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['zone_code'],
            },
        ),
        migrations.CreateModel(
            name='FiringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_sequence', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '待试烧'), ('firing', '试烧中'), ('pending_retest', '待复测'), ('adjusting', '调整中'), ('approved', '可定样'), ('suspended', '暂停使用')], default='pending', max_length=20)),
                ('kiln_in_time', models.DateTimeField(blank=True, null=True)),
                ('kiln_out_time', models.DateTimeField(blank=True, null=True)),
                ('color_difference', models.CharField(blank=True, choices=[('none', '无'), ('slight', '轻微'), ('high', '偏高'), ('severe', '严重')], default='', max_length=20)),
                ('pinhole_condition', models.CharField(blank=True, choices=[('none', '无'), ('minor', '少量'), ('moderate', '中等'), ('severe', '严重')], default='', max_length=20)),
                ('glaze_flow_desc', models.TextField(blank=True, default='')),
                ('retest_conclusion', models.TextField(blank=True, default='')),
                ('handling_suggestion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firing_records', to='ceramics.bodytype')),
                ('glaze_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firing_records', to='ceramics.glazecolor')),
                ('kiln_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firing_records', to='ceramics.kilnbatch')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firing_records', to='ceramics.responsibleperson')),
                ('temperature_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firing_records', to='ceramics.temperaturezone')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('kiln_batch', 'trial_sequence')},
            },
        ),
    ]
