# Generated by Django 4.2.10 on 2026-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0002_alter_firingrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firingrecord',
            name='adjust_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firingrecord',
            name='adjust_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firingrecord',
            name='approve_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firingrecord',
            name='retest_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firingrecord',
            name='suspend_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
