# Generated by Django 4.2.10 on 2026-06-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0003_firingrecord_adjust_count_firingrecord_adjust_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('anomaly_type', models.CharField(choices=[('color_diff_high', '色差偏高'), ('color_diff_severe', '色差严重'), ('pinhole_moderate', '针孔中等'), ('pinhole_severe', '针孔严重'), ('suspended', '暂停状态')], max_length=30)),
                ('anomaly_description', models.TextField()),
                ('cause_category', models.CharField(blank=True, choices=[('formula', '配方问题'), ('process', '工艺问题'), ('kiln', '窑炉问题'), ('material', '原料问题'), ('operation', '操作问题'), ('other', '其他')], default='', max_length=30)),
                ('cause_detail', models.TextField(blank=True, default='')),
                ('rectification_measures', models.TextField(blank=True, default='')),
                ('planned_completion_date', models.DateField()),
                ('rectification_result', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_analysis', '待分析'), ('rectifying', '整改中'), ('pending_confirm', '待确认'), ('closed', '已关闭')], default='pending_analysis', max_length=30)),
                ('analysis_time', models.DateTimeField(blank=True, null=True)),
                ('rectification_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_time', models.DateTimeField(blank=True, null=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firing_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectification_orders', to='ceramics.firingrecord')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectification_orders', to='ceramics.responsibleperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
