# Generated by Django 4.2.10 on 2026-06-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0004_rectificationorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectificationorder',
            name='anomaly_type',
            field=models.CharField(choices=[('color_diff_high', '色差偏高'), ('color_diff_severe', '色差严重'), ('pinhole_moderate', '针孔中等'), ('pinhole_severe', '针孔严重'), ('suspended', '暂停使用'), ('retest_overdue', '复测超期')], max_length=30),
        ),
        migrations.CreateModel(
            name='RectificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建整改单'), ('analyze', '原因分析'), ('submit', '提交整改'), ('confirm', '确认关闭'), ('reopen', '退回整改'), ('update', '信息更新'), ('comment', '备注')], max_length=30)),
                ('action_display', models.CharField(blank=True, default='', max_length=50)),
                ('operator_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('current_status', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rectification_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='ceramics.rectificationorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
